"""APA citation navigation without inventing bibliographic metadata.

The research protocol supplies APA entries and stable reference anchors. Older
APA author-date reference lists can be anchored conservatively. Unrecognized
references and ambiguous author/year matches are retained, never guessed.
"""

import re
import unicodedata
from collections import Counter
from dataclasses import dataclass

ANCHOR = re.compile(r'<a id="(ref-[a-z0-9-]+)"></a>')
LINK = re.compile(r"\[([^\]\n]+)\]\(#(ref-[a-z0-9-]+)\)")
SECTION = re.compile(r"^##\s+(?:References|Bibliography)\s*$", re.M | re.I)
YEAR = re.compile(r"\((\d{4}[a-z]?|n\.d\.)(?:,\s*[^)\n]+)?\)\.")
PROTECTED = re.compile(r"(```[\s\S]*?```|`[^`\n]*`|!?\[[^\]\n]*\]\([^\n)]*\)|<[^>]*>)")


@dataclass(frozen=True)
class CitationDocument:
    markdown: str
    reference_count: int
    citation_count: int
    warnings: tuple[str, ...] = ()


def _slug(text: str) -> str:
    ascii_text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode()
    return re.sub(r"[^a-z0-9]+", "-", ascii_text.lower()).strip("-")


def _label(entry: str) -> tuple[str, str] | None:
    plain = re.sub(r"^\s*(?:[-*]|\d+\.)\s+", "", entry).lstrip("*")
    year = YEAR.search(plain)
    if not year:
        return None
    authors = plain[: year.start()].strip()
    names = re.findall(r"(?:^|,\s*(?:&\s*)?)([^,]+),\s*(?:[A-ZÀ-ÖØ-Þ]\.\s*)+", authors)
    if names:
        label = names[0].strip()
        if len(names) > 2:
            label += " et al."
        elif len(names) == 2:
            label += " & " + names[1].strip()
    elif "," not in authors and authors:
        label = authors.rstrip(".")
    else:
        return None
    return label, year.group(1)


def prepare_citations(text: str) -> CitationDocument:
    """Idempotent navigation pass. APA wording comes from source metadata."""
    section = SECTION.search(text)
    if not section:
        return CitationDocument(
            text,
            0,
            0,
            (
                "No APA reference list was identified; original source links were retained.",
            ),
        )
    # Strip only navigation generated by this module before rebuilding it.
    text = re.sub(r'<a id="cite-ref-[a-z0-9-]+-\d+"></a>', "", text)
    text = re.sub(r"\n\n\[Back to citation[^\n]*", "", text)
    section = SECTION.search(text)
    body, refs = text[: section.start()], text[section.end() :]
    next_section = re.search(r"^#{1,2}\s+", refs, re.M)
    suffix = ""
    if next_section:
        suffix, refs = refs[next_section.start() :], refs[: next_section.start()]
    # Blank-line paragraphs are the protocol's entry boundaries. Normalize
    # numbered/bulleted legacy lists only when each item is a separate line.
    refs = re.sub(r"\n(?=\s*(?:\d+\.|[-*])\s+\S)", "\n\n", refs)
    blocks = re.split(r"\n\s*\n", refs.strip())
    ambiguous_ids = {
        key for key, count in Counter(ANCHOR.findall(refs)).items() if count > 1
    }
    entries = []
    pending = ""
    used_ids: set[str] = set()
    warnings = []
    for block in blocks:
        if ANCHOR.fullmatch(block.strip()):
            pending = block.strip()
            continue
        block = pending + block
        pending = ""
        anchor = ANCHOR.search(block)
        content = ANCHOR.sub("", block).strip()
        parsed = _label(content)
        if not parsed:
            entries.append((None, None, block))
            continue
        label, year = parsed
        ref_id = anchor.group(1) if anchor else "ref-" + _slug(f"{label}-{year}")
        if ref_id in used_ids:
            warnings.append(
                "Duplicate reference identifiers were found; ambiguous citations need review."
            )
            ref_id += "-" + str(len(entries) + 1)
        used_ids.add(ref_id)
        content = re.sub(r"^\s*(?:[-*]|\d+\.)\s+", "", content)
        # APA DOI URLs should be live links in Markdown as well as PDF.
        parts = PROTECTED.split(content)
        for i in range(0, len(parts), 2):
            parts[i] = re.sub(
                r"https?://[^\s<>]+",
                lambda m: "["
                + m[0].rstrip(".,;")
                + "]("
                + m[0].rstrip(".,;")
                + ")"
                + m[0][len(m[0].rstrip(".,;")) :],
                parts[i],
            )
        entries.append((ref_id, (label, year), "".join(parts)))
    if pending:
        entries.append((None, None, pending))
    counts = Counter(label for _, label, _ in entries if label)
    # Convert plain author-date mentions only when there is exactly one match.
    parts = PROTECTED.split(body)
    for ref_id, label, _ in entries:
        if not ref_id or counts[label] != 1:
            continue
        author, year = label
        pattern = re.compile(
            r"(?<![\w])"
            + re.escape(author)
            + r"(?:,\s*"
            + re.escape(year)
            + r"|\s*\("
            + re.escape(year)
            + r"\))"
        )
        for i in range(0, len(parts), 2):
            parts[i] = pattern.sub(lambda m: f"[{m[0]}](#{ref_id})", parts[i])
    body = "".join(parts)
    labels_by_id = {ref_id: label for ref_id, label, _ in entries if ref_id}
    occurrences: dict[str, list[str]] = {}

    def link(match):
        ref_id = match[2]
        if ref_id not in used_ids or ref_id in ambiguous_ids:
            warnings.append(
                "A citation points to a missing reference; review the source list."
            )
            return match[1]
        cited_year = re.search(r"\b(\d{4}[a-z]?|n\.d\.)", match[1])
        if cited_year and cited_year[1] != labels_by_id[ref_id][1]:
            warnings.append(
                "A citation date differs from its reference; the ambiguous link was not added."
            )
            return match[1]
        locations = occurrences.setdefault(ref_id, [])
        cite_id = f"cite-{ref_id}-{len(locations) + 1}"
        locations.append(cite_id)
        return f'<a id="{cite_id}"></a>{match[0]}'

    pieces = PROTECTED.split(body)
    body = "".join(
        LINK.sub(link, piece) if i % 2 == 0 or LINK.fullmatch(piece) else piece
        for i, piece in enumerate(pieces)
    )
    output = []
    # Preserve unrecognized material; alphabetize recognized APA entries only
    # when the section consists entirely of them.
    if entries and all(ref_id for ref_id, _, _ in entries):
        entries.sort(key=lambda entry: entry[2].casefold())
    for ref_id, _, content in entries:
        if not ref_id:
            output.append(content)
            continue
        locations = occurrences.get(ref_id, [])
        backlinks = " · ".join(
            f"[Back to citation {i}](#{location})"
            for i, location in enumerate(locations, 1)
        )
        output.append(
            f'<a id="{ref_id}"></a>{content}'
            + (f"\n\n{backlinks}" if backlinks else "")
        )
    if any(count > 1 for count in counts.values()):
        warnings.append(
            "Some author/year references are ambiguous; use verified a/b year suffixes to distinguish them."
        )
    return CitationDocument(
        body + "## References\n\n" + "\n\n".join(output) + "\n\n" + suffix,
        len(used_ids),
        sum(map(len, occurrences.values())),
        tuple(dict.fromkeys(warnings)),
    )
